# Generated by Django 5.0.1 on 2025-12-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idvend',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
